import type { Metadata } from "next"

import ChackraProvider from "./chackra-provider"
import Header from "./components/header"
import { Container } from "@chakra-ui/react"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<ChackraProvider>
					<Header />
					<Container as='main' maxW='container.xl' p={4}>
						{children}
					</Container>
				</ChackraProvider>
			</body>
		</html>
	)
}
